package com.upm.institutional.controller;

import com.upm.institutional.config.SecurityConfig;
import com.upm.institutional.model.Role;
import com.upm.institutional.model.User;
import com.upm.institutional.repository.FeatureRepository;
import com.upm.institutional.repository.UserRepository;
import com.upm.institutional.service.CustomUserDetailsService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIfSystemProperty;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.jdbc.datasource.init.ScriptUtils;
import org.springframework.test.web.servlet.MockMvc;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestBuilders.formLogin;
import static org.springframework.security.test.web.servlet.response.SecurityMockMvcResultMatchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(AdminController.class)
@Import({SecurityConfig.class, CustomUserDetailsService.class})
class AdminLoginTest {
    @Autowired MockMvc mvc;
    @MockBean UserRepository users;
    @MockBean FeatureRepository features;

    @BeforeEach
    void seedAccountFromMigration() throws Exception {
        var db = new EmbeddedDatabaseBuilder().generateUniqueName(true)
                .setType(EmbeddedDatabaseType.H2).build();
        try (var connection = db.getConnection()) {
            var migration = new ClassPathResource("db/migration/V19__add_recovery_admin.sql");
            connection.createStatement().execute("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username VARCHAR(255) UNIQUE, password_hash VARCHAR(255), role VARCHAR(20), enabled BOOLEAN)");
            ScriptUtils.executeSqlScript(connection, migration);
            ScriptUtils.executeSqlScript(connection, migration);
            try (var result = connection.createStatement().executeQuery("SELECT * FROM users")) {
                assertTrue(result.next());
                var user = new User();
                user.setUsername(result.getString("username"));
                user.setPasswordHash(result.getString("password_hash"));
                user.setRole(Role.valueOf(result.getString("role")));
                user.setEnabled(result.getBoolean("enabled"));
                assertEquals(Role.ADMIN, user.getRole());
                assertTrue(user.isEnabled());
                assertFalse(result.next(), "Migration must not create duplicates");
                when(users.findByUsername("admin_upm")).thenReturn(Optional.of(user));
            }
        } finally {
            db.shutdown();
        }
    }

    @Test
    @EnabledIfSystemProperty(named = "recovery.admin.password", matches = ".+")
    void newAdminCanLogin() throws Exception {
        mvc.perform(formLogin("/admin/login").user("admin_upm")
                        .password(System.getProperty("recovery.admin.password")))
                .andExpect(authenticated().withUsername("admin_upm").withRoles("ADMIN"))
                .andExpect(redirectedUrl("/admin/dashboard"));
    }

    @Test
    void wrongPasswordIsRejected() throws Exception {
        mvc.perform(formLogin("/admin/login").user("admin_upm").password("wrong-password"))
                .andExpect(unauthenticated())
                .andExpect(redirectedUrl("/admin/login?error"));
    }

    @Test
    void dashboardRequiresLogin() throws Exception {
        mvc.perform(get("/admin/dashboard"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrlPattern("**/admin/login"));
    }
}
